server:
  port: ${vcap.application.port:9009}

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
  client:
    registerWithEureka: true
    fetchRegistry: true
